CREATE TABLE IF NOT EXISTS "casts"
(
	ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	Filename TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS "comments"
(
	ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	CastID INTEGER NOT NULL,
	Author TEXT NOT NULL,
	Message TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "views"
(
	ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	CastID INTEGER NOT NULL,
	IP TEXT NOT NULL,
	Timestamp TEXT NOT NULL
);
